---
#-------------------------------
# General Site Settings

title: Unlock-AI
logo: /assets/images/unlock-ai_logo.png
author: gautamborgohain
description: AI and Data Science Consulting - Form Prototype to Production
email: hello@unlock-ai.sg
phone: +65 9494 9494
address:
copyright: Copyright &copy; 2020 Unlock-AI.sg and Theme designed by [Themefisher](https://themefisher.com)

menu:
  - { name: About, link: "/about" }
  # - { name: Blog, link: "/blog" }
  # - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Get your startup funding with done-for-you prototypes
  hero-sub-title: Unlock AI builds cost-effective, high-speed AI prototypes for startups, helping you secure investment without the need for early hiring.

# social:
# - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/gautamborgohain90/" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: We are team of Data Scientists, Software Engineers and Technologists with deep expertise in data analysis, experimentation and Artifical Intelligence. We can help you use your data to drive business growth.

blurb-btn-link: "/about"
blurb-btn-name: Contact Us

# About Page

# Work Process Section
work-process:
  - title: "Discovery"
    icon: "assets/images/icons/discovery.png"
    content: "Understanding your business, goals, and current data landscape."

  - title: "Analysis, Modeling & POC development"
    icon: "assets/images/icons/modeling.png"
    content: "Applying advanced techniques to uncover insights and develop solution proof of concepts."

  - title: "Delivery & Integration"
    icon: "assets/images/icons/delivery.png"
    content: "Deploying solutions and integrating them into your existing systems"

  - title: "Monitoring & Optimization"
    icon: "assets/images/icons/monitoring.png"
    content: "Monitoring performance and making improvements to ensure sustained success."

# My Team Section
team:
  - title: "Jack Schenziwe"
    image: "assets/images/team/member-1.png"
    designation: "Project Manager"

  - title: "Julias Carlie"
    image: "assets/images/team/member-2.png"
    designation: "Web Developer"

  - title: "John Doe"
    image: "assets/images/team/member-3.png"
    designation: "Designer"

#-------------------------------
# Skills Section

skills-title: How can AI help ?
skills:
  - { name: Large Language Models, color: "#bdecf6", value: "90%" }
  - { name: Predictive analytics, color: "#fdb157", value: "90%" }
  - { name: Customer Retention, color: "#9473e6", value: "90%" }
  - { name: Recommendations Systems, color: "#ffbcaa", value: "90%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Assoc. Principal Data Scientist,
      icon: "dyson_logo.png",
      date: "Mar 2024 - Present",
      organization: "Dyson",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Marters in UX Design,
      date: "2006",
      organization: "Masassusets Institute of Technology",
    }
  - {
      name: Honours in Fine Arts,
      date: "2004",
      organization: "Harvard University",
    }
  - {
      name: Higher Secondary Certificat,
      date: "2000",
      organization: "Cardiff School",
    }
  - {
      name: Secondary School Certificate,
      date: "1998",
      organization: "Cardiff School",
    }

#-------------------------------
# Services Section

services-title: What you get
services-sub-title: AI Prototypes - Scaling from 1->1000
services:
  - {
      name: Data Science and AI Consulting,
      icon: ti-stats-up,
      description: "Leverage advanced analytics and AI to solve business challenges and drive strategic growth.",
      active: false,
    }
  - {
      name: POC Development,
      icon: ti-bar-chart,
      description: "Rapidly validate and demonstrate the feasibility of data-driven AI / Gen AI solutions with tailored proof of concepts.",
      active: true, # Add true to select section
    }
  - {
      name: Process Optimization,
      icon: ti-support,
      description: "Streamline operations and enhance efficiency through data-driven process improvements.",
      active: false,
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Want to learn how we can Unlock efficiency with AI ? <br><br> Drop us a message !
contact-email: myzggwlq
